version: '3'

services:
  master:
    image: locustio/locust
    ports:
      - "8089:8089"
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/main.py --master -H http://localhost:8089
    network_mode: "host"

  worker:
    image: locustio/locust
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/main.py --worker --master-host localhost
    environment:
      - OKTA_DOMAIN=dev-8885869.okta.com
      - OKTA_CLIENT_ID=0oa13hy3cuQJZao2Y5d7
      - OKTA_CLIENT_SECRET=_cH5jTnBzM5I6HHQJWvKpXGmmuc__InwTSPp936c
      - INTAKE_USER=jintake@milleniumcare.com
      - INTAKE_PASSWORD=1hotmonk
    network_mode: "host"